### ISSUE TITLE
[Bug Report]: "ESP-IDF Build, Flash and Monitor" will not flash through JTag (VSC-647)

### ISSUE THREAD

**Issue by pearson** [espressif/vscode-esp-idf-extension#392]
I'm not certain if this is a bug or something I'm missing, but it smells like a bug...

If I build a project and then use the "ESP-IDF Flash device" button (or the "ESP-IDF: Flash (with JTag)" command), all is well and I get a JTag flash through a ESP-PROG to a ESP32 device. However, if I use the "ESP-IDF Build, Flash and Monitor" button (or command), the flash process attempts to do a UART flash through a non-existent COM1 port.

This is on Windows 10 with the current ESP-IDF and with openocd-esp32-win32-0.10.0-esp32-20210401. 

The `settings.json` in the project directory was set by "ESP-IDF: Select OpenOCD Board Configuration" and contains:
```yaml
{
"C_Cpp.intelliSenseEngine": "Tag Parser",
"idf.adapterTargetName": "esp32",
"idf.openOcdConfigs": [
	"interface/ftdi/esp32_devkitj_v1.cfg",
	"target/esp32.cfg"
],
"idf.flashType": "JTAG"
}
```

My assumption is that there shouldn't be another setting to tell it "no, really, I want JTag flashing", but perhaps I'm missing something. 😄

**Comment by pearson** [comment]
An important point that I missed in my initial post is that I left out the `idf.portWin` parameter from the `settings.json` example intentionally. With a correct `idf.portWin`, "ESP-IDF Build, Flash and Monitor" will flash using UART rather than JTag, even though the `idf.flashType` parameter is set to `"JTAG"`. 

For example:
```yaml
{
"C_Cpp.intelliSenseEngine": "Tag Parser",
"idf.openOcdConfigs": [
	"interface/ftdi/esp32_devkitj_v1.cfg",
	"target/esp32.cfg"
],
"idf.adapterTargetName": "esp32",
"idf.portWin": "COM3",
"idf.flashType": "JTAG"
}
```

Leaving out the `idf.portWin` parameter simply pointed to the fact that "ESP-IDF Build, Flash and Monitor" was always flashing with UART.
